### ISSUE TITLE
global funtions

### ISSUE THREAD

**Issue by medarin** [EdgeTX/edgetx.github.io#16]
when making a global function for volume the menu on the left shows switch, func, volume, and enable but when doing one for backlight it shows switch, func, value, and enable..

**Comment by pfeerick** [comment]
This is in the wrong repo. Please close and repost in https://github.com/EdgeTX/edgetx ;)

When do you, please also clarify what the the actual issue is here - Volume showing volume, but Backlight showing value? Do you think value should be showing value as well, or that backlight should be showing something else instead of value?
